name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          username: vboxuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3128
          script: |
            cd /home/vboxuser/lab3/catty-reminders-app
            git fetch origin
            git reset --hard origin/lab4
            export APP_IMAGE=ghcr.io/vissstu/catty-reminders-app:${{ github.sha }}
            export DEPLOY_REF=${{ github.sha }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_DATABASE=catty_reminders
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose up -d --pull always --remove-orphans --force-recreate
            docker image prune -f
